### ISSUE TITLE
Review API exposure reference solution document

### ISSUE THREAD

**Issue by jordonezlucena** [camaraproject/WorkingGroups#1]
https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/API-exposure-reference-solution.docx

**Comment by T-sm** [comment]
Thank you for preparing this document, it has been already praised by multiple participants during the Commonalities Workgroup meetings.
Our colleague Marcin Jarząb has remarks concerning figure 6 (mapping of CAPIF components into CAMARA reference architecture):
- can the picture explicitly present “CAMARA Exposure GW” – it is not clear if the “yellow box” is the entity (CCF + API Provider DF)? Please add label CAMARA Exposure GW;
- Shouldn't the API Invoker as Vertical App have arrow only to CAPIF API black box via Proxy mechanism?
- because CAPIF API Framework provides Access Control, API Invoker should not call CAPIF 2e interface directly (maybe use a dashed line);
 - Please note that AMF is already present in 5G core (Access & Mobility Management Function) therefore using this acronym for API Management Function could introduce ambiguity.

Thanks again!

**Comment by jordonezlucena** [comment]
Hi @T-sm. See my responses inline below.

>> can the picture explicitly present “CAMARA Exposure GW” – it is not clear if the “yellow box” is the entity (CCF + API Provider DF)? Please add label CAMARA Exposure GW;
The yellow box represents CAMARA focus, which includes TRANSFORMATION FUNCTION + EXPOSURE GW. In the figure, exposure GW can be mapped to CAPIF (CCF + API provider domain functions). I can emphasize more on these ideas in a new version. Thanks.

>> Shouldn't the API Invoker as Vertical App have arrow only to CAPIF API black box via Proxy mechanism?
This needs further discussion, I think. We'll definitely needed CCF for everything about API discovery, publishing, registry and access control. But when coming to API consumption, the API Invoker might directly go through CAPIF-2e, and be the API provider domain functions act as API providers, and the actual enforcers of the authorization. After reading CAPIF spec, I think this approach is possible. But I think it's a matter a decision for us -- we don't need to strictly follow CAPIF solution set, but the most practical approach. We have had the same discussion at 3GPP SA5, because we have a work item around capability exposure, and we're facing the same issue as you have pointed out. So definitely this needs further discussion. 

>> because CAPIF API Framework provides Access Control, API Invoker should not call CAPIF 2e interface directly (maybe use a dashed line);
See previous response.

>>Please note that AMF is already present in 5G core (Access & Mobility Management Function) therefore using this acronym for API Management Function could introduce ambiguity.
Good point, but please note that SA6 uses AMF terminology as well. But ok not to use here in CAMARA to avoid confussion.
