### ISSUE TITLE
Unified Notfication/Event management

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/WorkingGroups#156]
As we have notification in several of our API (and probably we'll have more moving forward), it will make sense to get an unified way to subscribe to them and then to describe notification.

**subscription:**
For the subscription we should probably align on the attributes name & description (in order to have the same in all APIs);

I'm also wondering if it would make sense to manage persistent subscription, as, of now, it is only one time notification subscription (I have to ask for a notification and provide notification url & token for each call). We can imagine to add hub pattern to manage subscription (app x want to get all QoD session event from its session at a given url - a hub is created once)

**notification:**
In order to simplify the API from developers perspective, perhaps we can have one simple notification structure for all our APIs.
This structure could be something like this:

- eventType - mandatory - String --> the title of the event like PaymentStatusChange (for Carrier billing) or SessionEvent (for Qod), etc...
- timeOcurred - mandatory - datetime --> When the event occurred
- eventDetail - object --> payload defined for each camara API

I propose to draft a chapter on this in the guideline but looking before to your feedback.
Thanks

**Comment by sfnuser** [comment]
@bigludo7 - Thanks for driving this effort.
Have we also thought about the [Authentication & Authorization aspects](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA-AuthN-AuthZ-Concept.md) for notification? Does the entity that receives `notification` (from a CAMARA API service) need to authorize the API service? Will authentication alone with TLS be enough? Just raising the question for discussion.

**Comment by bigludo7** [comment]
Hello @sfnuser and thanks for your support.
I'm not sure we can go deep inside the authentifcation & authorization pattern in a guideline document. But, it could probably be documented in a recommendation or best practice document.

For me in the guideline we have 'injunction' that must apply to all API. We could all agree on an event schema for example en enforce this for all APIs. All aspects related to security could not probably be injunctive as I tend to think that each company security demand prevails. 

But perhaps I missed the point here.

Thanks

**Comment by bigludo7** [comment]
Hello @sfnuser 
Thanks for your comments.

For `timeOccurred` this is a valid point to discuss. For we can have 2 distinct 'kind' of dates
- Technical one - a timestamp when the event was raised and this one should be part of the event generic structure.
- Business one - that are linked specifically to the event type (like datetime a device entered in a area, date when a carrier billing payment was processing) and this ones should be in `eventDetail`

Perhaps this is too much ? For you, the technical one is not necessary ? I was thinking of having it in order to sort event on listener side.

For the event subscription - yes it needs discussion. Today we have a mechanism to subscribe notification per request (for example in the carrier billing api you provide a notificationUrl in the POST payment --> for each payment request you have to provide each time this notificationUrl). I'm thinking that for some UC we could do it another way: suppose we have an aggregator or an hyperscaler using our api we could perhaps provide them a mechanism to subscribe once for a type of event (of course only for their resources). It will allow to avoid having notificationUrl & notificationAuthTokenon the 'wire' in each call. 

Agree with you, a `context` must be passed in this subscription but we could use the `eventType` for this.

Happy to discuss thi!

**Comment by bigludo7** [comment]
One good point mentioned by @jlurien in Device Location stream - We need to have rules when a subscription is targeting several user equipment.

If for any reason the subscription could not be done for some ue (due to problem with consent for example) does we just accept the subscription for a subset or do we reject completely the subscription request?

I have a preference for the later but looking for feedback.

**Comment by PedroDiez** [comment]
Good point @bigludo7. And thanks to raised it.

Internally in Telefonica we are discussing about this topic (notifications subscription management, notifications securitization, notifications body format,...) in order to enrich this thread and share our view for this interesting discussion.

This is a traversal point and the discussion/consensus/aggrements reached about it should be handled here and not within specific WGs. After the conclusions reached here, we can go in a aligned way in those APIs that may need this kind of features.

**Comment by PedroDiez** [comment]
Topics regarding this issue:

**Securitization Topics**: As already mentioned in this thread.

- At transport level: Think in CAMARA we can agree in the use of TLS for `notificationUrl` endpoints. Therefore that implies our "consumers" MUST provide HTTPs endpoints for receiving notifications. Suggest to include some indication of this in the notification section guidelines so everyone must define these endpoints using some kind of pattern to enforce use of HTTPs.

- At application level: Checking [PR#173](https://github.com/camaraproject/WorkingGroups/pull/173), the model proposed relies on the use of a `notificationAuthToken` indicated by the API consumer, so it is inserted in the way back from the Server to the `notificationUrl` endpoint provided by API consumer. We think this solution have some drawbacks/challenges:

- > Uniqueness of this "token" is not ensured 100%. The system that generates the "token" is the API Consumer, so in a widespread ecosystem, potential scenario of having two identical "tokens" may happen.

- > Scalability: It is foreseen that we, as Telco operators, will have to manage up to Millions of notifications, so it is highly probably we will have to manage M of different "token" each of them can have associated a different lifecycle, so it adds complexity to notifications server implementation

- >  Randomness: We need to ensure randomness regarding the generation of these tokens, to avoid incremental sequential OR pattern-based deployments, as this may generate security lackings on the API consumer side.

-> Functionality: It may be also understood like a correlator functionality than a securitization mechanism, so API Consumer can easily identify which specific flow this notification belongs to.

Then, think that we need to clearly define how that "token" has to be used, to indicate how it has to be used in the communication and porbably have some conventions in his format to enhnace implementations associated to it.

Additionaly, we think we can provide additional securitization towards API consumers by providing signing (with a private_key) the request body (i.e. signing the notification body or notification payload -i.e. eventDetail-) so we can add that signature to the notification and progress to the API consumer, and also providing an endpoint to the API consumers so they can fetch the public key and validate the signature. Signature features provides "message integrity" so we think it is a good way to indicate our clients that such notifications comes from our systems, generating trustability 


**Notification topics**: Agree in principle it is a good approach to have a common notification model where some traversal information can apply to every notifications and specific information is managed within an object, that can be customized/modelled with the details of the different scenarios we can have in CAMARA APIs. Need to check PR in detail to provide comments


**subscription topics**: One doubt here @bigludo7, have seen in the PR the "Resource-based subscription" model. The approach is to define a model we can re-use and define in the APIs that may require it? Or the proposal is to have a common separate API where susbcriptions for any CAMARA API notifcations can be managed.

**Comment by sfnuser** [comment]
@PedroDiez 

>Additionaly, we think we can provide additional securitization towards API consumers by providing signing (with a private_key) the request body (i.e. signing the notification body or notification payload -i.e. eventDetail-) so we can add that signature to the notification and progress to the API consumer, and also providing an endpoint to the API consumers so they can fetch the public key and validate the signature. Signature features provides "message integrity" so we think it is a good way to indicate our clients that such notifications comes from our systems, generating trustability

Not sure why we need signing and maintenance of extra private key?
Already we are sending notifications via HTTPS(TLS) which does provide `message integrity` feature. If the client is worried about sender `Identity`, we could easily upgrade this to mTLS as all the API services will have valid certificates to verify their identity with client.

I still don't understand the usage of `token` here.

**Comment by shilpa-padgaonkar** [comment]
I have also always understood it to be an Oauth2 token.  

We should also make sure that we do not contradict our existing approved commonalities documents when adding content to the guidelines doc. I noticed such a problem already and have created an issue for this https://github.com/camaraproject/WorkingGroups/issues/197

**Comment by sfnuser** [comment]
@eric-murray @shilpa-padgaonkar 
I too remember `notificationAuthToken` was meant to be an OAuth2 token when this topic was started. But in the PR #173 it is defined as something else. Hence, I posted the question here besides commenting on the PR.

Even if we define this as an OAuth2 token - is this going to be `id_token` or `access_token`? Considering the client uses `clientCredentials` OAuth2 flow to access the API, it has to be `access_token` I suppose. For `instance` based notification subscription that is supposed to be there forever, lifecycle of `access_token` without a way to refresh it makes unuseful. A leaked token can be replayed by anyone without a time limit.

Besides, in the context of event notification procedure, I am not sure about the benefit OAuth2 token provides. Not sure about the use of say `scope` to provide varied `access` in the case of an event notification. Please share some use cases where an OAuth2 `access_token` would be useful here.

I agree on rejecting `http` notificationUrl. The PR #173 names `https` as the only option, which is good.

The client (notification receiver) needs some method to identify the event invoker. As discussed above, I am not so convinced with the usage of passing and replaying OAuth2 tokens in messages to determine `identity`. The simplest solution could be the usage of mTLS as the necessary resources are already there at both the client and API service and it resolves the `identity` issue. This could be a guideline and need not be enforced upon by CAMARA. As you suggested, mTLS could be mentioned as optional but it is good to mention this in our guidelines. Without mTLS, anybody can spoof a API server and flood the critical `notification` endpoint making it unavailable.

@eric-murray - As you mentioned, I am not keen on the restriction that both the server & client needs to be signed by the same CA, considering the flexibility of deployment options available today. To me, mTLS ensures both the talking endpoints are indeed the endpoints as advertised. The client implementation can further enforce network rules or gateway filters to ensure only the intended server endpoints are allowed to reach the client in the first place. As you suggested, CAMARA may not even need to say anything on CA certs aspect. Operators are free to choose their own strategy.

Regarding security of notification, the document can be updated to provide minimal guidelines as suggested - like reject http, use mTLS etc. This way CAMARA is not encouraging opening up endpoints without any basic consideration of security. Operators shall choose further strategies that suits there deployment.

**Comment by eric-murray** [comment]
@sfnuser 

Yes, good points.

> Even if we define this as an OAuth2 token - is this going to be id_token or access_token? Considering the client uses clientCredentials OAuth2 flow to access the API, it has to be access_token I suppose. For instance based notification subscription that is supposed to be there forever, lifecycle of access_token without a way to refresh it makes unuseful. A leaked token can be replayed by anyone without a time limit.

For the API provider, the token is just a string to be included in the `Authorization` header. The API provider should not be concerned with the lifetime of the token or refreshing it. But I agree a mechanism is required for the client (API caller) to periodically update the token if spoofed notifications are a concern for them. But let's not overstate the risk or consequences of spoofed notifications. The API caller can decide.

> @eric-murray - As you mentioned, I am not keen on the restriction that both the server & client needs to be signed by the same CA, considering the flexibility of deployment options available today. To me, mTLS ensures both the talking endpoints are indeed the endpoints as advertised.

All that verifying the client certificate for mTLS really shows is that the client (in this case, the API provider) knows the private key. And when it was the server that issued the certificate / key in the first place, that is sufficient. But in this case, the API provider will generate their own client certificate, so of course they know the private key. It is not manageable for CAMARA APIs that each API caller provides separate client certificates for the API provider to use when sending notifications.

So the question for the API caller when receiving a notification is not "has the client certificate been validated", but "do I trust that specific certificate, or at least the CA that signed that certificate". I agree that it should not be mandated that the same CA as the API provider server certificate be used for practically reasons, But if mTLS is to be used, maybe some guidance should be given that the API provider publish their client certificate used for notifications or, if that is not practical, at least publish the root CA certificate used to sign client certificates if different from their own server certificate.

**Comment by sfnuser** [comment]
@eric-murray

>>Even if we define this as an OAuth2 token - is this going to be id_token or access_token? Considering the client uses clientCredentials OAuth2 flow to access the API, it has to be access_token I suppose. For instance based notification subscription that is supposed to be there forever, lifecycle of access_token without a way to refresh it makes unuseful. A leaked token can be replayed by anyone without a time limit.

>For the API provider, the token is just a string to be included in the Authorization header. The API provider should not be concerned with the lifetime of the token or refreshing it. But I agree a mechanism is required for the client (API caller) to periodically update the token if spoofed notifications are a concern for them. But let's not overstate the risk or consequences of spoofed notifications. The API caller can decide.

I agree, it is not API provider's concern. 
However, if the token is to be used in Authorization header as in standard practice with basic auth, OAuth2 procedures, we need to document what type of token it is and it's purpose - authentication or authorization? - for the client's (API user) to know and implement. If it is indeed an OAuth2 `access_token` whose standard purpose is `authorization`, we should `not` define in the guidelines that it is to be used for `authentication` - against standard procedures. If this `access_token` to be used for `authorization`, we are not providing a way to check it's validity, refresh and use it (i.e.) we are recommending in the API guidelines to treat it as `opaque` string and replay it, which is a non-standard way of using `access_token` and I am not comfortable with it. I also don't understand what we achieve by doing this.

If the `token` is not an OAuth2 token and some non-standard string (as mentioned in the PR like a UUID) and it's purpose is for correlating a subscription & an event, probably we should rename `notificationAuthToken` as `correlationId` or something like that and remove all the wording of authentication. This `correlationId` should rather be used in the message body and not in the `Authorization` header.

>All that verifying the client certificate for mTLS really shows is that the client (in this case, the API provider) knows the private key. And when it was the server that issued the certificate / key in the first place, that is sufficient. But in this case, the API provider will generate their own client certificate, so of course they know the private key. It is not manageable for CAMARA APIs that each API caller provides separate client certificates for the API provider to use when sending notifications.

I think there is some misunderstanding. I do not understand the need for API caller to provide separate client certificate for the API providers (or) the need to publish root CA.

Let's take a real world deployment scenario. I am an API user/notification aggregator `www.camara-api-notifications.mycompany.com`. I get my signed certificate from a well known CA like Symantec by proving that I own this domain. A CAMARA API provider exposes their APIs at endpoints `www.camara-api.provider.com/qod`, `www.camara-api.provider.com/devicestatus`. The API provider gets a signed cert from another well know CA like GoDaddy for the domain `*.provider.com`. The respective deployment OS/trust-store of the aggregator and provider will already have the root CAs of all well known CAs including Symantec and GoDaddy.

When the aggregator subscribes to the API provider (or) when the API provider posts an event to the aggregator, each endpoint can independently verify the other endpoint because they MUST already have the root CAs of well known CAs (otherwise they cannot establish TLS in the first place - how would the notification aggregator trust the API provider without the GoDaddy root CA?). This is why I mentioned mTLS is a simple to establish in this case as both the notification aggregator and API provider are public CA verified endpoints.

If it is a lab deployment scenario where the notification aggregator and API provider are within the same network/domain, of course they are free to self sign their certificates with their own root CA and add this root CA to their trust-store at both the aggregator and provider endpoints. This is needed for TLS too - for the notification aggregator to trust the API provider.

**Comment by eric-murray** [comment]
@sfnuser 

> However, if the token is to be used in Authorization header as in standard practice with basic auth, OAuth2 procedures, we need to document what type of token it is and it's purpose - authentication or authorization?

I understood it was for authorisation. So I think the agreement should be that, if the API caller includes `notificationAuthToken`, then the API provider will include the following header in any notifications:
`Authorization: Bearer <notificationAuthToken>`

> I think there is some misunderstanding. I do not understand the need for API caller to provide separate client certificate for the API providers (or) the need to publish root CA.

Yes, indeed.

First, my proposal is that the API **provider** generate their own client certificate and publish that or, at least, the root CA certificate (if not "well-known") so that the API caller can verify it when used for notifications (where the API provider is acting as a client and the API caller as server).

Second, in your example, I understand that notifications would be sent to `https://www.camara-api-notifications.mycompany.com` with the server certificate validated in the usual way. But what client certificate would the API provider use? You appear to be suggesting that it should use the **very same server certificate** that is used to validate `https://www.camara-api.provider.com`.

That is a major restriction. I doubt I would be readily be given access to the server certificate private key just so that I can implement mTLS for callbacks. It is important to realise that notifications may come from separate infrastructure with a separate interfaces (and hence separate IP addresses) from the primary API gateway. I'm surprised that using a server certificate as a client certificate would be considered "normal" for this type of use case, but I have only limited experience of API infrastructure implementations.

So the possibility that the API provider server certificate and client certificate are different certificates needs to be allowed, and the possibility that the CA for the client certificate is not a "well-known" CA also needs to be allowed. Otherwise API providers may view mTLS for notifications as "too difficult".

Final point is that I don't think a **client** certificate with CN = `camara-api.provider.com` is **sufficient** to prove the identity of the client. It depends on who signed it, and even then the DNS check at the time of use would be missing. It should be up to the API caller to decide what client certificates could be trusted, but this decision needs to be made on the basis of information made available by the API provider about the client certificate they are using.

**Comment by sfnuser** [comment]
@eric-murray 

>I understood it was for authorisation. So I think the agreement should be that, if the API caller includes notificationAuthToken, then the API provider will include the following header in any notifications:
Authorization: Bearer <notificationAuthToken>

Agreed. However, this is not the definition I see in the PR and that is how this thread started :-)
@bigludo7 @PedroDiez could you please clarify? If it is indeed OAuth2 `access_token`, we need to address the questions I have posted earlier.

>Second, in your example, I understand that notifications would be sent to https://www.camara-api-notifications.mycompany.com with the server certificate validated in the usual way. But what client certificate would the API provider use? You appear to be suggesting that it should use the very same server certificate that is used to validate https://www.camara-api.provider.com.

>That is a major restriction. I doubt I would be readily be given access to the server certificate private key just so that I can implement mTLS for callbacks. It is important to realise that notifications may come from separate infrastructure with a separate interfaces (and hence separate IP addresses) from the primary API gateway. I'm surprised that using a server certificate as a client certificate would be considered "normal" for this type of use case, but I have only limited experience of API infrastructure implementations.

I was merely pointing out with an example mTLS scenario, where publishing a rootCA is not a MUST that it needs to be mentioned in the API guidelines. How an operator implements mTLS in their deployment is upto them.

>So the possibility that the API provider server certificate and client certificate are different certificates needs to be allowed, and the possibility that the CA for the client certificate is not a "well-known" CA also needs to be allowed. Otherwise API providers may view mTLS for notifications as "too difficult".

Indeed. There should be no restriction enforced by the guideline as these are all valid mTLS use cases.

>Final point is that I don't think a client certificate with CN = camara-api.provider.com is sufficient to prove the identity of the client. It depends on who signed it, and even then the DNS check at the time of use would be missing. It should be up to the API caller to decide what client certificates could be trusted, but this decision needs to be made on the basis of information made available by the API provider about the client certificate they are using.

Agreed. Like TLS, mTLS alone does not ensure fool proof identity of the endpoints but it is a widely used standard for this purpose. As a guideline in the specification, we can recommend its usage similar to the `https` recommendation. It is upto the operator and their deployment to add additional measures.

**Comment by PedroDiez** [comment]
Regarding "signing": @bigludo7, @sfnuser, @eric-murray, @shilpa-padgaonkar 

> Additionaly, we think we can provide additional securitization towards API consumers by providing signing (with a private_key) the request body (i.e. signing the notification body or notification payload -i.e. eventDetail-) so we can add that signature to the notification and progress to the API consumer, and also providing an endpoint to the API consumers so they can fetch the public key and validate the signature. Signature features provides "message integrity" so we think it is a good way to indicate our clients that such notifications comes from our systems, generating trustability

Intention is to manage this as a separate issue. We see it as an improved way to provide more security. Let's not consider within Issue#156/PR#173 discussion.

Let's discuss in a separate the proposal, I am elaborating it and now focus on initial API design guidelines
