### ISSUE TITLE
Reference NEF

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/WorkingGroups#26]
For contributing code we need a reference NEF on which the code can be based.
Identify suche a NEF for CAMARA.

**Comment by jordonezlucena** [comment]
- We support this proposal. 
- We support having more than one NEF implementation, e.g. Nokia's NEF, Ericsson's NEF. Individual operators can then decide among which one(s) they want to validate service APIs.
- Each NEF implementation should be made available together with the micro service implementing the logic of 'service API-to-network API' transformation. Without this micro service, there is no real value on having a NEF implementation.

**Comment by petorre** [comment]
Within Intel program "Smart Edge Open" we built NEF complete with minimum features, implementing API+schema https://www.openness.org/api-documentation/?api=nef , in two versions:

- "Previous", Apache 2 licensed version, in public repository https://github.com/smart-edge-open/epcforedge
- "Current", Intel-licensed version for "efforts to develop and distribute solutions running on Intel-based products", that also comes with source. Packaged binary image we could contribute now to appropriate testbed.

If this is relevant as Reference NEF option, here are few possible steps in order:

1. Start now with "previous" version binary (I can build/install, or provide detailed instructions on how to do it), and Apache 2 source
2. On "Intel-based products" testbed use "current" version binary (I can build/install)
3. See if any features are missing - last the development team updated it in 2021, closing on all customer requests we had at the time
4. Ask if "current" version or next version could be licensed Apache 2 because of Camara community usage

We can discuss more on next calls.

**Comment by Kevsy** [comment]
Good idea - but we should include a reference SCEF (or equivalent mapping) to also support EPC.

**Comment by shilpa-padgaonkar** [comment]
@petorre : In the public repo for Nef package there are currently 2 NEF APIs implemetned -
Trafficinfluence and PFDManagement. AsSessionWithQoS is not part of the package.
Could you kindly check with your team if the AsSessionWithQoS API is available as part of the private repo?
Thanks.

**Comment by jordonezlucena** [comment]
Apart from NEF emulator, EVOLVED-5G also brings open-source implementation of CAPIF services. This project is focused on testing and validating NetApps consuming 5GC capabilities.

**Comment by shilpa-padgaonkar** [comment]
A new issue for documentation of the Nokia openlab NEF can be opened when contribution from Nokia is ready. Marked this issue as stale and closing.
