### ISSUE TITLE
Proposals to simplify the table BacklogAPI.md

### ISSUE THREAD

**Issue by hdamker** [camaraproject/WorkingGroups#307]
While creating #306 i learned that it is almost impossible to maintain the status of an existing sub project within the BacklogAPI.md. To ease the maintainance here some proposals.

First: the table could be converted into a HTML table format. That would ease the maintainance (as the table elements would get own lines). For an example of HTML table in MD file see [here](https://github.com/camaraproject/QualityOnDemand/blob/release-0.8.1/documentation/API_documentation/QoD_API.md).

Potential general simplification: 
* APIBacklog.md contains mainly the information which is collected until a sub project is decided and created
* plus potentially link to (only the) latest release of the sub project (no history)
* plus potentially list of the APIs within the project (links should be in the README.md of the subproject)
A release history is (should be) maintained within the CHANGELOG.md of each sub project.

Comments on some columns which are obviously not maintained in current table and might be omitted from it:
* column "API deployed at company and county" ... this information does not fit into a short status line and will always be incomplete, proposal to omit
* same for "tested at" (if then should this information maintained in an agreed way within the project)
* link to API code ... it's only relevant for implementors, it would be enough to have this information within the sub project README
* "link to documentation" ... will be inline in YAML going forward. Swagger editor & Redoc links could make sense

**Comment by ShutingQing** [comment]
Good suggestions. The table header is too long, which causes it hard to move to the rightest columns. 

Potential general simplification:

- APIBacklog.md contains mainly the information which is collected until a sub project is decided and created - **Agree,**
- plus potentially link to (only the) latest release of the sub project (no history) - **Agree,**
- plus potentially list of the APIs within the project (links should be in the README.md of the subproject) - **Agree,** api can be shown in readme, and link to read me.
- A release history is (should be) maintained within the CHANGELOG.md of each sub project. - **Agree,** history of 20+apis will be too much, should be managed in changelog in each proj

Comments on some columns which are obviously not maintained in current table and might be omitted from it:

- [ ] column "API deployed at company and county" ... this information does not fit into a short status line and will always be incomplete, proposal to omit - **This info is valueable, suggest to keep it?** 
- [ ] same for "tested at" (if then should this information maintained in an agreed way within the project) - **This info is valueable, suggest to keep?** 
- [ ] link to API code ... it's only relevant for implementors, it would be enough to have this information within the sub project README - **Agree**
- [ ] "link to documentation" ... will be inline in YAML going forward. Swagger editor & Redoc links could make sense - **Agree** 

**Others:**
- [ ] **link to API definition** ... main content of each sub project, **suggest to omit** as well
- [ ] **TSC decision** ... how about **only leave approve or not?**

**Comment by jordonezlucena** [comment]
We need to have one single table that captures all relevant information at a glance, specially for newcomers. This was an explicit request from project chair, and also something that has been requested for long time by individual companies. That's why this [figure](https://github.com/camaraproject/Governance/blob/main/documentation/images/API_overview_list.png)
) was drafted. Who is responsible for maintaining which information can be summarised as follows: 
- Sub-Project leader: API name, API release, Link to API definition, Link to API documentation
- Individual companies: API tested at, API deployed at company and country


Please find below, my feedback...

General simplification
- [ ] APIBacklog.md contains mainly the information which is collected until a sub project is decided and created - **We need to have one single table that captures all relevant information regarding API lifetime, from their proposal until their testing/deployment, with all the stages in between. And we need this to be shown at a glance**.
- [ ] plus potentially link to (only the) latest release of the sub project (no history) - **Agree**
- [ ] plus potentially list of the APIs within the project (links should be in the README.md of the subproject) - **Agree**
- [ ] A release history is (should be) maintained within the CHANGELOG.md of each sub project. - **Agree**


Comments on some columns which are obviously not maintained in current table and might be omitted from it
- [ ] column "API deployed at company and county" ... this information does not fit into a short status line and will always be incomplete, proposal to omit - **Not sure about this, we need to capture into one single table information covering the entire lifecycle stages of an API, and that also includes deployment**
- [ ] same for "tested at" (if then should this information maintained in an agreed way within the project) - ***Not sure about this, we need to capture into one single table information covering the entire lifecycle stages of an API, and that also includes testing**
- [ ] link to API code ... it's only relevant for implementors, it would be enough to have this information within the sub project README - **Agree**
- [ ] "link to documentation" ... will be inline in YAML going forward. Swagger editor & Redoc links could make sense - **Fine whatever the selected format** 

@hdamker: how do you suggest to move this forward? I think this is not something that can be agreed upon internally in API backlog WG, since this decision affects the overall project. @MarkusKuemmerle  and TSC should be involved as well in this discussion, in my opinion.

**Comment by hdamker** [comment]
@ShutingQing @jordonezlucena: thanks for your comments. There seem to be several points we agree on.

I still think that the current APIBacklog.md in its current form and tooling is only suitable to cover the life cycle until a sub project is created. For the other purposes, especially the overview of sub projects & API lifecycle status we need to find another tooling:

- It's too complicated to edit and the process to update data points by sub project "leads" (btw: a role not defined within the governance, there are only maintainers) is too time consuming. My PR #306 is waiting since three weeks for review/merge and QoD seems to be the only one ever done inputs on the last columns of the table.
- It is also not suitable for consumers of the table ... here an example how it looks for me (independent how large I make my browser window, I need always to scroll horizontically):
![APIBacklog_view](https://github.com/camaraproject/WorkingGroups/assets/52109189/c4e4a98b-b66f-4405-b3c0-afefb47308d3)

Said this I also agree that we need an overview table about the sub projects, their status, latest release etc. Let's park this issue until we have our wiki ([wiki.camaraproject.org](https://wiki.camaraproject.org)) properly setup and then see if we can setup a table there which is easier to maintain and read. I have even the hope that LF can help us, to have one status page per project which then populates such table automatically.

**Comment by hdamker** [comment]
Replaced by https://github.com/camaraproject/Governance/issues/100. Will close here, but discussion content could be still considered for the new issue.
