### ISSUE TITLE
New Proposal - OGW Call Forwarding signal

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/WorkingGroups#359]
Part of OGW Drop 3.

|The Application Function (AF) of the Service calls the Call Forwarding Signal API (provided by the OP) to determine if a specific MSISDN has an active call forwarding setup

**Comment by jordonezlucena** [comment]
Don't forget to link this issue to the PR with the filled-in application template by this Thursday EoB.

**Comment by jordonezlucena** [comment]
@FabrizioMoggio: Do you have a proposal on which sub-project should host this API? Is it an existing Sub-Project or a new one (in such a case, which is the sub-project name you propose)? This is valuable input for the TSC when making their decision.

In the event of a new Sub-Project, a new repo should be created, with maintainers/codeowners from a least TWO companies. As for now, this API proposal has only Telecom Italia as supporting company, so it'd be good to look for another supporting company.

**Comment by FabrizioMoggio** [comment]
@jordonezlucena If there was an API Family gathering all the anti fraud/scam APIs (IMEI Fraud, Sim Swap etc.) I would suggest to put the Call FWD API there. Not having it, I propose to create a new sub-project, but I'm open to suggestions.

The new sub-project name could simply be "CallForwardingSignal".

Because we need a second partner for a new sub-project to be opened: here is a call for action to the community. **Is there a volunteer interesting in co-leading the Call FWD API**?

**Comment by FabrizioMoggio** [comment]
I'm checking with GSMA OGW Product Stream and OPAG for a possible  Use Case for fixed networks. The CAMARA APIs are Use Case driven, so we need a use case to justify the features of an API. So far we just have a Use Case for mobile networks. Anyway I don't see a real problem because, as for any other API, if a new Use Case for fixed networks will come in the future the API scope can be extended with a new release.

**Comment by HuubAppelboom** [comment]
@FabrizioMoggio Are you sure there are no use cases for an fixed network API that does the same thing ?   What is the mobile use case ?  Is it when the mobile number is authenticated with a phone call ?

One use case I can think of is CEO fraud. As a fraudster you may walk into some CEO office, and when unattended forward a fixed line to your mobile phone.  Then you try to have a fraudulent order executed at the bank of the victim. When the bank calls the CEO back to make sure it is the CEO, you pick up the phone. If you ask me this can just as well work on fixed lines as on mobile lines.  So why bother to make a mobile-only restriction ?

**Comment by FabrizioMoggio** [comment]
@HuubAppelboom thank you for proposing a possible use case, we are interested in fixed aspects too, we just would like to start covering **a concrete use case that can have an immediate outcome in the market**.   

Unfortunately the UC you proposed doesn't fit this purpose, if I got it correctly. Let me explain:

The UC we are currently working on is fulfilling a concrete scenario, it is an integration for **system already in place in the Bank**. Currently already exist applications that, **programmatically**, contact the customer smartphone. These applications can invoke the Call FWD API before placing the call to the customer. To any customer, and the device known and certified by the bank is the mobile device. The bank is able to certify the mobile device, usually via SMS.

The scenario you proposed, is actually a fraud, you are totally right, but I don't see in the use case **an automated system calling a fixed phone** because it is not certified. And even if it could be possible, for specific relevant people (a CEO), **I don't see anyway this callback done via an automated system that can invoke an API** . On top of this we have also to consider that an office fixed number is often behind an IVR or a directory system. I can't see an automated system interacting in this scenario.

Don't get me wrong, it is not that we don't want a fixed use case, the point is that we suggest to work on something on which we already see a potential market, this because **the SBI interface for this API are not standard** and I see many possible discussions for the network integration that can have an impact on the intent based definition of the API. And **if we start considering both mobile and fixed network the complexity raises a lot**. **For this reason I suggest to start simple**, covering a use case we know is of interest of the market with a possible integration in already existing systems.

Obviously if we come out with a concrete use case **supported by a business need** (this is our main driver, isn't it?) we can for sure expand the API to also cover the new use case.

 We did like this in the Traffic Influence API, we started simple with a basic use case (LBO) and than, when the API was stable enough, we introduced a much more complex use case (user mobility) and everything worked pretty well. This because we were able to shape the API starting from something simple.

**Comment by bigludo7** [comment]
Hi @FabrizioMoggio 
Perhaps I did it wrong but I added my comment in the PR here: https://github.com/camaraproject/WorkingGroups/pull/361 

Hope, as it is coming for real life UC, that you'll consider it.

**Comment by FabrizioMoggio** [comment]
@bigludo7 sure we will consider it. 

please have a look on my answer here: https://github.com/camaraproject/WorkingGroups/pull/361#issuecomment-1880559780

**Comment by jordonezlucena** [comment]
Thanks both @HuubAppelboom and @FabrizioMoggio for the discussion on the scope of the API proposal (mobile-only vs mobile + fixed). While we have quorum on the need for mobile domain to be included in the scope of the original API, there is no consensus on the mobile domain. 
It is true that we have some freedom in CAMARA to decide details of an Open Gateway API proposal,  including final name (which can diverge from original GSMA name) and scope, specially when the proposal leave them (intentionally or unintentionally) open. So deciding "mobile-only" or "mobile + fixed" are both fine. But according to the experience in the past, it's better to start with a very concrete market-empowered use case (and thus a narrower scope), and grow from that point over time. This facilitates evolution (evolution of Device Location is a very good example on how an API can be enriched with new features over time).

**Comment by FabrizioMoggio** [comment]
We have ORANGE as second maintainer: https://github.com/camaraproject/WorkingGroups/pull/374.

Once PR 374 is merged, and the "mobile only" scope is agreed, we can proceed with TSC approval for a new WG named "CallForwardingSignal".

**Comment by jordonezlucena** [comment]
Following the [minutes](https://wiki.camaraproject.org/display/CAM/2024-01-11+API+Backlog+minutes) of last conf. call, there is an action for all operators to declare their position on the scope of API (see AP 20240111-03).
Two options for the scope:
1) "Mobile-only" in the first API version. 
2) Mobile+fixed (mobile lines + landlines) in the first API version. 

WG coordinator recommendation is to go for option 1, as posted earlier. 
TIM (API owner) preference is to go for option 1. @FabrizioMoggio suggests focusing on the expected biggest market opportunity around mobile lines, leaving landlines for a second version of the API.
@HuubAppelboom: would option 1 doable for you?

**Comment by FabrizioMoggio** [comment]
> Neither:
> 
> * We will not support any standard where fixed or mobile telco's are excluded without a technical reason to do so
> * For the mobile+fixed version, we don't see sufficient market demand here
> * For a mobile devices, there is already an option to include this in the Mobile Connect ATP standard which we support in NL. So, if we are going to implement this mobile-only, we can also add it here. Most customers for this check will want to have a SIM swap check done as well, so if you ask me this will be much faster in stead of using separate 2 API calls.

@HuubAppelboom, with regards to your first and second points, the whole Open Gateway initiative is about the development of APIs driven by Business uses cases. Technical reasons are not the drivers for the implementation or not of features in an API. To be honest I don't see a difference for the NBI intents in terms of fixed or mobile scope, anyway I suggest to focus on what we have as requirements from the market and currently we just have proved business use case for a mobile device. I really don't see the problem, it is not that we are excluding a fixed use case, we just suggest to start developing the API with the mobile use case in mind.   

In the third point, I'm not sure to get your suggestion. Are suggesting to include the Call FWD Signal feature in another CAMARA API or in an existing standard?

**Comment by HuubAppelboom** [comment]
@FabrizioMoggio The first point I mention is more of a principle, that we don't want to be involved in activities that can be explained as a restriction competition between parties, for example by a fixed line competitor.  The specification for a call forwarding signal will probably the same for fixed lines or mobile lines, so a mobile-only restriction van easily be explained as a form of hindering competition.

For the third point, in the Mobile Connect standard for SIM Swap (ATP, see https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.24-Mobile-Connect-Account-Takeover-Protection-Definition-and-Technical-Requirements-v2.0.pdf) , the call forwarding signal is included as an optional feature.

In case your customer always wants to check the CAMARA SIM Swap API as well, it may be better to make the Call Forward signal an option in te CAMARA Sim Swap API as well, because then you will only need to go once through the authentication part of the flow, and in case you require user consent to be collected, only one time a user consent.  That will save a lot of time in the flow, which is probably important in case you use it for a 2FA solution.

**Comment by FabrizioMoggio** [comment]
Dear @HuubAppelboom I see you point but I think there is a misunderstanding. **We  are not proposing a mobile only API**,  we are just considering a mobile use case **first**. This argument of yours would be against any other CAMARA API (mostly all of them) targeting mobile only use cases. Many CAMARA APIs could, in theory, address both fixed and mobile use cases, anyway, most of the times, they are designed around a mobile use case. This choice has an effect on the API documentation (where the usage of the API is explained via examples) and on the choices on the SBI to be used. We are just proposing to keep it simple now and we will add the fixed use case as soon as a good one is identified. Wrapping up, you are totally right about being careful not to limit the competition but this is not the case in my opinion.

Honestly, I really don't see an API named SIM Swap to be invoked to get the call fwd status. I see your point on the SBI API, so we can evaluate to use the same SBI API also for the Call FWD API but  SIM SWAP and Call FWD are two totally different functionalities.

**Comment by bigludo7** [comment]
I'm fine with option 1 as well and from my perspective one of the main point (as you mentioned @FabrizioMoggio) is to build a consistent YAML that can handle both mobile & landline.

Regarding the other point raised by @HuubAppelboom 

> For the third point, in the Mobile Connect standard for SIM Swap (ATP, see https://www.gsma.com/identity/wp-content/uploads/2022/12/IDY.24-Mobile-Connect-Account-Takeover-Protection-Definition-and-Technical-Requirements-v2.0.pdf) , the call forwarding signal is included as an optional feature.
In case your customer always wants to check the CAMARA SIM Swap API as well, it may be better to make the Call Forward signal an option in te CAMARA Sim Swap API as well, because then you will only need to go once through the authentication part of the flow, and in case you require user consent to be collected, only one time a user consent. That will save a lot of time in the flow, which is probably important in case you use it for a 2FA solution.


As of now, as we have a fine granular in the CAMARA APIs (and no optional feature)  I tend to think that having a separate CAMARA API for Call forward Signal make sense. If you look to device status or Device location for example you'll see that we have distinct endpoint and/or distinct API for 'close' features. But this is fair point to be considered and I propose for this point:

- to be checked in the SIM swap project (Does this team consider that Call Forward Signal is part of their scope?)
- must be specifically mentioned during TSC.

@FabrizioMoggio @HuubAppelboom WDYT?

**Comment by HuubAppelboom** [comment]
@FabrizioMoggio @bigludo7   I would suggest to check with the customer what they want first, and whether they will always want to have SIM Swap checked as well.   If the duration of the API calls is no issue for them, a granular approach may be best, if response time is critical, and they also need SIM Swap data, it may be best to combine the API's.

In the Netherlands we don't have such a voice authentication customer, maybe you can check @FabrizioMoggio  with your customer?

(For the NL cases we have they are not that time critical, so forus it is not that important).

**Comment by jordonezlucena** [comment]
@FabrizioMoggio @HuubAppelboom:
-  CAMARA focus is API definition (input/output parameters and endpoints in the YAML file). How this API definition translates southbound and which business cases results from implementation is on operator discretion, and thus out of CAMARA realm -- maybe this is a discussion that qualifies better for OGW project level (product definition WS, local markets, etc.). 
- From CAMARA standpoint, if the fixed/mobile aspect does not impact API definition, I suggest parking the discussion and moving forward, since it is totally transparent for CAMARA API consumers.

**Comment by FabrizioMoggio** [comment]
@HuubAppelboom, @jordonezlucena, @bigludo7 thank you all for your good suggestions. For sure the API covers both mobile & landline. I just think it is important to provide the Developer with a clear use case for him to identify the value of the API, this is way I suggested to start including in the YAML documentation the mobile use case we have identified so far. Obviously, if a concrete use case for landlines is identified we can integrate it. Anyway we will implement the API as neutral with respect to fixed and mobile access. 

About having the Call Fwd feature included in Sim Swap, our customers requested a specific API but it is a fair point so I will also investigate in GSMA Product WS. Anyway, let's just consider that including both SIM Swap and Call FWD in the same API can be appropriate if the intent is "is there a fraud?", so the API name can't be SIM Swap. And, by the way, the whole fixed-mobile "thing" is no more valid.

**Comment by jordonezlucena** [comment]
Hi @HuubAppelboom @FabrizioMoggio: let's find a way forward on the API proposal. 
- It seems API definition does not stick to a specific segment (mobile and cable), so that's good. 
- About the specification of use cases in the API documentation, I very much agree with @FabrizioMoggio. The documentation shall capture concrete and market-supported use cases. So far we don't have a concrete use case for landline. In the near future, if someone brings one that makes sense, then for sure will be integrated. But as of today, that's not the case, so I suggest starting with mobile use cases.

If there is no agreement on this way forward before the meeting this Thursday, I will then be forced to invoke the decision making procedure defined in [ProjectCharter](https://github.com/camaraproject/Governance/blob/main/ProjectCharter.md#decision-making), calling for a majority vote accordingly.

**Comment by FabrizioMoggio** [comment]
@jordonezlucena I agree on your proposal

**Comment by jordonezlucena** [comment]
Regarding the decision-making, I've been flagged that we cannot do a majority vote within the Working Group as there is no defined group of people eligible to vote (in sub projects that are the maintainers, but the API Backlog working group has no such list). If no consensus can be reached, **the matter may be resolved by majority vote by the TSC** (cc @hdamker).

@HuubAppelboom @FabrizioMoggio: let's avoid this escalation to TSC and try to reach a consensus within the backlog WG on the way forward proposed before (i. start the API development in a new sub project, initially with a mobile use case, but technically designed for use in mobile and fixed networks).

**Comment by HuubAppelboom** [comment]
@jordonezlucena @FabrizioMoggio If we can make the technical specification in susch a way that it does not use mobile terminology (like use phone number in stead of MSISDN), and with the use case description you describe only a mobile case, then I am fine with that.  The only thing we should not do is stating that it is not allowed to use this for landline applications.

**Comment by jordonezlucena** [comment]
It seems we're converging. @HuubAppelboom: could you please join tomorrow's call to nod you're ok with the [API proposal](https://github.com/camaraproject/WorkingGroups/pull/361/files)? Or is there anything that you want that gets modified in the actual proposal?

**Comment by HuubAppelboom** [comment]
I don;t have the invite in my agenda. Can you please forward it ?

Regards
Huub

**Comment by FabrizioMoggio** [comment]
codeowner/maintainer for Orange: @bigludo7

**Comment by chinaunicomyangfan** [comment]
codeowner/maintainer for ChinaUnicom: chinaunicomyangfan

**Comment by jordonezlucena** [comment]
According to the [draft minutes](https://wiki.camaraproject.org/display/CAM/2024-02-01+TSC+Minutes) of last TSC meeting, the API proposal has been approved. I'll send out the maintainer/codeowners as provided above, so the repo can be opened at the earliest.
