### ISSUE TITLE
How to address user consent for Camara APIs

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#60]

**Comment by eric-murray** [comment]
@shilpa-padgaonkar 
Consent management should not be addressed by CAMARA at all.

A mechanism must be provided by the API to identify and authenticate the API caller (i.e. OpenID Connect, which is already specified for the QoD API), and the target actors involved (UE, AS, etc.). Once these actors have been established, the API implementation can check if the API consumer has the required permissions (including any target actor consent) for the request to be processed. If not, then a 403 Forbidden error message can be returned.

If the relevant permissions are not in place for the request to be actioned, I do not think CAMARA need provide a mechanism for this to be resolved. Rather, the error message can include some support contact details, such as an e-mail or portal address, so that the API consumer can request support to obtain the necessary permissions. I would expect the mechanisms for establishing permissions and consent will be different in each CSP and will largely be an IT process. Trying to standardise mechanisms across CSPs will inevitably fail.

**Comment by jordonezlucena** [comment]
Hi, TEF believes user consent management will be recurrent in the usage of CAMARA APIs, specially those targeting B2C and B2B2C, and therefore this topic should be in scope of CAMARA. At TEF, we're working on a generic proposal (applicable to every telco) and we'd like to socialize it with Commonalities participants by the first week of September -- our main contact people helping us draft the proposal are on vacation until end of August.

**Comment by jordonezlucena** [comment]
Hi, the proposal is submitted via pull request -> https://github.com/camaraproject/WorkingGroups/pull/68.

**Comment by shilpa-padgaonkar** [comment]
As agreed in commonalities call, a request for dedicated subproject for identity and consent has been created here https://github.com/camaraproject/WorkingGroups/pull/116

**Comment by shilpa-padgaonkar** [comment]
@jordonezlucena: Would you agree to now close this PR https://github.com/camaraproject/WorkingGroups/pull/68, and I can close this issue so that the topic can be addressed in the newly created subproject?

**Comment by jordonezlucena** [comment]
Issue closed, since a dedicated Sub-Project has been defined for Identity and Consent. Here are the coordinates: https://github.com/camaraproject/IdentityAndConsentManagement. Please, add your name and affiliation in case you want to join discussions.
